#!/bin/sh
#
# @name Gazebo Classic YHANG550
#
# @type Quadrotor x
# @class Copter
#
# @maintainer PX4-RoboMaster
#

. ${R}etc/init.d/rc.mc_defaults

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# rotor 0: SDF position (+x, -y), CCW
param set-default CA_ROTOR0_PX 0.19445
param set-default CA_ROTOR0_PY 0.19445
param set-default CA_ROTOR0_KM 0.05

# rotor 1: SDF position (-x, +y), CCW
param set-default CA_ROTOR1_PX -0.19445
param set-default CA_ROTOR1_PY -0.19445
param set-default CA_ROTOR1_KM 0.05

# rotor 2: SDF position (+x, +y), CW
param set-default CA_ROTOR2_PX 0.19445
param set-default CA_ROTOR2_PY -0.19445
param set-default CA_ROTOR2_KM -0.05

# rotor 3: SDF position (-x, -y), CW
param set-default CA_ROTOR3_PX -0.19445
param set-default CA_ROTOR3_PY 0.19445
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104


param set-default MPC_THR_HOVER 0.60
